name: Build Dashboard

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2
    - name: Check out GitHub Pages branch
      uses: actions/checkout@v2
      with:
        ref: 'gh-pages'
        path: 'out'

    - name: 'Generate Dashboard'
      uses: ethomson/issue-dashboard@v1
      with:
        config: |
          title: 'Dashboard'
          output:
            format: html
            filename: 'out/index.html'
          sections:
          - title: 'Status'
            description: 'Current state of Catalyst Prioritized Problems board'
            widgets:
            - type: number
              issue_query: 'project:Catalyst-Circle/Catalyst-Prioritized-Problems/3 is:open is:issue created:>{{ date("-1000 days") }}'
              title: 'Total open Issues'
              color: 'blue'
            - type: number
              issue_query: 'project:Catalyst-Circle/Catalyst-Prioritized-Problems/3 is:issue created:>{{ date("-30 days") }}'
              title: 'Opened issues this month'
              color: 'red'
            - type: number
              issue_query: 'project:Catalyst-Circle/Catalyst-Prioritized-Problems/3 is:issue closed:>{{ date("-30 days") }}'
              title: 'Closed issues this month'
              color: 'green'
          - title: 'Circles'
            description: 'Issues per group'
            widgets:
            - type: graph
              title: Circle groups
              elements:
              - title: General ADA Holders
                issue_query: 'project:Catalyst-Circle/Catalyst-Prioritized-Problems/3 is:issue is:open label:'General Voters' created:>{{ date("-1000 days") }}'
                color: green
              - title: 'Community Advisors'
                issue_query: 'project:Catalyst-Circle/Catalyst-Prioritized-Problems/3 is:issue is:open label:'Community Advisor' created:>{{ date("-1000 days") }}'
              - title: 'Funded Proposers'
                issue_query: 'project:Catalyst-Circle/Catalyst-Prioritized-Problems/3 is:issue is:open label:'Funded Proposers' created:>{{ date("-1000 days") }}'
              - title: 'Toolmakers and Maintainers'
                issue_query: 'project:Catalyst-Circle/Catalyst-Prioritized-Problems/3 is:issue is:open label:'Toolmaker and Maintainer' created:>{{ date("-1000 days") }}'
                color: red
              - title: 'Stake Pool Operators'
                issue_query: 'project:Catalyst-Circle/Catalyst-Prioritized-Problems/3 is:issue is:open label:'SPOs' created:>{{ date("-1000 days") }}'
                color: red
          - title: 'Issues'
            widgets:
            - type: 'table'
              title: 'Issue Dashboard'
              issue_query: 'project:Catalyst-Circle/Catalyst-Prioritized-Problems/3 is:issue created:>{{ date("-1000 days") }} sort:created-asc'
              
        token: ${{ github.token }}

    - name: Publish Documentation
      run: |
        git add .
        git config user.name 'Dashboard User'
        git config user.email 'nobody@nowhere'
        git commit -m 'Documentation update' --allow-empty
        git push origin gh-pages
      working-directory: out
