name: Build Dashboard

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2
    - name: Check out GitHub Pages branch
      uses: actions/checkout@v2
      with:
        ref: 'gh-pages'
        path: 'out'

    - name: 'Generate Dashboard'
      uses: ethomson/issue-dashboard@v1
      with:
        config: |
          title: 'Dashboard'
          output:
            format: html
            filename: 'out/index.html'
          sections:
          - title: 'Status'
            description: 'Current state of Catalyst Prioritized Problems board'
            widgets:
            - type: number
              issue_query: 'project:Catalyst-Circle/Catalyst-Prioritized-Problems/3 is:open is:issue created:>{{ date("-1000 days") }}'
              title: 'Total open Issues'
              color: 'blue'
            - type: number
              issue_query: 'project:Catalyst-Circle/Catalyst-Prioritized-Problems/3 is:issue created:>{{ date("-30 days") }}'
              title: 'Opened issues this month'
              color: 'red'
            - type: number
              issue_query: 'project:Catalyst-Circle/Catalyst-Prioritized-Problems/3 is:issue closed:>{{ date("-30 days") }}'
              title: 'Closed issues this month'
              color: 'green'
          - title: 'Pizza preferences'
            description: 'Type of pizza preferred by respondents.'
            widgets:
            - type: graph
              title: Pizza variety
              elements:
              - title: New York
                value: 18
                color: green
              - title: Chicago
                value: 16
              - title: Neopolitan
                value: 15
              - title: 'New Haven'
                value: 1
                color: red
          - title: 'Issues'
            widgets:
            - type: 'table'
              title: 'Issue Dashboard'
              issue_query: 'project:Catalyst-Circle/Catalyst-Prioritized-Problems/3 is:issue created:>{{ date("-1000 days") }} sort:created-asc'
              
        token: ${{ github.token }}

    - name: Publish Documentation
      run: |
        git add .
        git config user.name 'Dashboard User'
        git config user.email 'nobody@nowhere'
        git commit -m 'Documentation update' --allow-empty
        git push origin gh-pages
      working-directory: out
